name: Build FriendlyWrt for NanoPi M4

on:
  workflow_dispatch:   # 手动触发
  schedule:
    - cron: "0 3 * * 1"   # 每周一早上 3 点自动构建

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git wget curl unzip python3 python3-pip \
            gawk gcc make libc-dev libncurses5-dev \
            zlib1g-dev libssl-dev flex bison g++ \
            repo

      - name: Init repo
        run: |
          mkdir project
          cd project
          repo init --depth=1 -u https://github.com/friendlyarm/friendlywrt_manifests \
                    -b master-v24.10 -m rk3399.xml \
                    --repo-url=https://github.com/friendlyarm/repo --no-clone-bundle
          repo sync -c friendlywrt --no-clone-bundle
          repo sync -c device/friendlyelec --no-clone-bundle
          repo sync -c scripts --no-clone-bundle
          repo sync -c toolchain --no-clone-bundle

      - name: Add luci-app-ssr-plus
        run: |
          cd project/friendlywrt/package
          mkdir -p custom
          cd custom
          git clone --depth=1 https://github.com/fw876/helloworld.git
          mv helloworld/luci-app-ssr-plus ./
          rm -rf helloworld

      - name: Build FriendlyWrt
        run: |
          cd project
          ./build.sh nanopi_m4.mk

      - name: Package rootfs
        run: |
          mkdir -p artifact
          cd project/out
          tar czf ../../artifact/rootfs-friendlywrt-nanopi-m4-24.10.tgz friendlywrt_*

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: friendlywrt-nanopi-m4
          path: artifact/rootfs-friendlywrt-nanopi-m4-24.10.tgz

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifact/rootfs-friendlywrt-nanopi-m4-24.10.tgz
          asset_name: rootfs-friendlywrt-nanopi-m4-24.10.tgz
          tag: nanopi-m4-v24.10
          overwrite: true
