name: FriendlyWrt 每周构建

on:
  schedule:
    - cron: '0 2 * * 1'   # 每周一 2:00
  workflow_dispatch:

jobs:
  prepare_release:
    runs-on: ubuntu-22.04
    steps:
      - name: 生成发布标签
        id: release_tag
        run: |
          RELEASE_TAG="FriendlyWrt-$(date +'%Y-%m-%d')"
          echo "RELEASE_TAG=${RELEASE_TAG}" >> $GITHUB_ENV
          echo "##[set-output name=release_tag;]$RELEASE_TAG"

      - name: 创建 Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.release_tag.outputs.release_tag }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_friendlywrt:
    needs: prepare_release
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        VERSION: ['23.05', '24.10']
        SET: ['docker', 'non-docker']
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 初始化环境
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential unzip wget git python3-distutils libncurses5-dev zlib1g-dev
          curl -fsSL https://get.docker.com | sh || true
          sudo usermod -aG docker $USER

      - name: 下载 FriendlyWrt rootfs
        uses: robinraju/release-downloader@v1.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repository: ${{ github.repository }}
          tag: ${{ needs.prepare_release.outputs.release_tag }}
          fileName: "rootfs-friendlywrt-${{ matrix.VERSION }}${{ matrix.SET == 'docker' && '-docker' || '' }}.tgz"
          out-file-path: ./friendlywrt
          latest: false
          tarBall: false
          zipBall: false

      - name: 解压 rootfs
        run: |
          mkdir -p project
          tar xvzf ./friendlywrt/rootfs-friendlywrt-${{ matrix.VERSION }}${{ matrix.SET == 'docker' && '-docker' || '' }}.tgz -C project

      - name: 仅拉 SSR Plus+ feed
        run: |
          cd project
          mkdir -p package/custom
          echo "src-git custom https://github.com/ophub/luci-app-ssr-plus.git" > feeds.conf.custom
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig

      - name: 编译 FriendlyWrt
        run: |
          cd project
          make -j$(nproc) || make -j1 V=s

      - name: 打包 rootfs
        run: |
          cd project
          mkdir -p ../artifact
          ROOTFS_TGZ="rootfs-friendlywrt-${{ matrix.VERSION }}${{ matrix.SET == 'docker' && '-docker' || '' }}.tgz"
          tar czf ../artifact/${ROOTFS_TGZ} *

      - name: 上传 rootfs 到 Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./artifact/${ROOTFS_TGZ}
          asset_name: ${ROOTFS_TGZ}
          tag: ${{ needs.prepare_release.outputs.release_tag }}
          overwrite: true
