name: FriendlyWrt 编译 NanoPi M4

on:
  workflow_dispatch: # 手动触发
  schedule:
    - cron: '0 2 * * 1' # 每周一凌晨 2 点自动构建

env:
  FRIENDLYWRT_VERSION: v24.10
  CPU: rk3399

jobs:
  prepare_environment:
    runs-on: ubuntu-22.04
    steps:
      - name: 安装依赖工具
        run: |
          sudo apt update
          sudo apt install -y unzip wget zlib1g-dev git curl python3 python3-pip
      - name: 安装 Docker
        run: |
          if ! command -v docker &> /dev/null
          then
            curl -fsSL https://get.docker.com | sh
          else
            echo "Docker 已安装，跳过"
          fi
      - name: 配置 GitHub Actions 用户
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'noreply@github.com'

  download_rootfs:
    needs: prepare_environment
    runs-on: ubuntu-22.04
    steps:
      - name: 下载 FriendlyWrt rootfs
        uses: robinraju/release-downloader@v1.6
        with:
          repository: friendlyarm/friendlywrt
          tag: ${{ env.FRIENDLYWRT_VERSION }}
          fileName: "rk3399-rootfs-${{ env.FRIENDLYWRT_VERSION }}.tgz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_friendlywrt:
    needs: download_rootfs
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        SET: [docker, non-docker]
    steps:
      - name: 准备编译目录
        run: |
          mkdir -p project
          cd project
          tar xvzf ../rk3399-rootfs-${FRIENDLYWRT_VERSION}.tgz
          cd friendlywrt
          mkdir -p package/custom
          echo "src-git custom https://github.com/ophub/luci-app-ssr-plus.git" > feeds.conf.custom
      - name: 更新并安装 feed
        run: |
          cd project/friendlywrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: 配置默认编译
        run: |
          cd project/friendlywrt
          make defconfig
      - name: 编译 FriendlyWrt + SSR Plus+
        run: |
          cd project/friendlywrt
          if [ "${{ matrix.SET }}" == "docker" ]; then
            make -j$(nproc) V=s
          else
            make -j1 V=s
          fi

  package_release:
    needs: build_friendlywrt
    runs-on: ubuntu-22.04
    steps:
      - name: 创建 Release
        id: release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "FriendlyWrt-${{ env.FRIENDLYWRT_VERSION }}-NanoPiM4"
          name: "FriendlyWrt ${FRIENDLYWRT_VERSION} NanoPi M4 镜像"
          body: "包含最新 SSR Plus+ LuCI 插件，可直接刷入 NanoPi M4"
          draft: false
          prerelease: false
      - name: 上传镜像到 Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: project/friendlywrt/bin/targets/rockchip/armv8/*/friendlywrt-*.img
          asset_name: "friendlywrt-${{ env.FRIENDLYWRT_VERSION }}-nanopi-m4-${{ matrix.SET }}.img"
          tag: ${{ steps.release.outputs.tag_name }}
          overwrite: true
