name: Build NanoPi M4 SSR Plus+ SD Image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # 每周一次，周日 00:00 UTC

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      ROOTFS_URL: "https://github.com/<your-repo>/friendlywrt-rootfs/releases/download/<tag>/rootfs-nanopi-m4.tgz"
      IMAGE_NAME: "FriendlyWrt-NanoPi-M4-SSRPlus"
      IMG_SIZE_MB: 4096   # SD卡大小
      BOOT_SIZE_MB: 128   # boot分区大小
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git gzip tar xz-utils parted dosfstools rsync qemu-user-static kpartx

      - name: Prepare rootfs
        run: |
          mkdir -p workspace/rootfs
          cd workspace/rootfs
          wget -O friendlywrt-rootfs.tgz $ROOTFS_URL
          tar xzf friendlywrt-rootfs.tgz

      - name: Add SSR Plus+ package
        run: |
          cd workspace/rootfs
          mkdir -p package/custom
          git clone --depth=1 https://github.com/ophub/luci-app-ssr-plus.git package/custom/luci-app-ssr-plus

      - name: Create SD image with boot + rootfs partitions
        run: |
          mkdir -p workspace/image
          IMG_FILE="workspace/image/${IMAGE_NAME}.img"
          dd if=/dev/zero of=$IMG_FILE bs=1M count=$IMG_SIZE_MB

          # 分区
          parted -s $IMG_FILE mklabel msdos
          parted -s $IMG_FILE mkpart primary fat32 1MiB ${BOOT_SIZE_MB}MiB
          parted -s $IMG_FILE mkpart primary ext4 ${BOOT_SIZE_MB}MiB 100%

          # 创建 loop 设备
          LOOPDEV=$(sudo losetup --show -fP $IMG_FILE)
          sudo mkfs.vfat ${LOOPDEV}p1
          sudo mkfs.ext4 ${LOOPDEV}p2

          # 挂载 rootfs
          sudo mkdir -p /mnt/boot /mnt/rootfs
          sudo mount ${LOOPDEV}p2 /mnt/rootfs
          sudo rsync -a workspace/rootfs/ /mnt/rootfs/
          sudo umount /mnt/rootfs

          # 可选：挂载 boot 分区复制 boot 文件（如果 rootfs 中有 boot）
          if [ -d workspace/rootfs/boot ]; then
            sudo mount ${LOOPDEV}p1 /mnt/boot
            sudo rsync -a workspace/rootfs/boot/ /mnt/boot/
            sudo umount /mnt/boot
          fi

          sudo losetup -d $LOOPDEV

          # 压缩镜像
          gzip -c $IMG_FILE > ${IMG_FILE}.gz

      - name: Create GitHub release
        id: release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ env.IMAGE_NAME }}-$(date +%Y-%m-%d)"
          name: "${{ env.IMAGE_NAME }} $(date +%Y-%m-%d)"
          draft: false
          prerelease: false

      - name: Upload SD image
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: workspace/image/${IMAGE_NAME}.img.gz
          asset_name: ${IMAGE_NAME}.img.gz
          tag: ${{ steps.release.outputs.tag_name }}
