name: Build FriendlyWrt NanoPi M4

on:
  workflow_dispatch: {}           # 手动触发
  schedule:
    - cron: '0 3 * * 0'          # 每周日 03:00 自动触发

jobs:
  prepare_release:
    runs-on: ubuntu-22.04
    steps:
      - name: Get release tag
        id: release_tag
        run: |
          release_tag="FriendlyWrt-$(date +%Y-%m-%d)"
          echo "release_tag=$release_tag" >> $GITHUB_ENV

      - name: Create empty release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.release_tag }}
          draft: false
          prerelease: false
    outputs:
      release_tag: ${{ env.release_tag }}

  build_friendlywrt:
    needs: prepare_release
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        SET: [docker, non-docker]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Init environment
        run: |
          sudo rm -rf /etc/apt/sources.list.d
          wget https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh
          sed -i -e 's/^apt-get -y install openjdk-8-jdk/# apt-get -y install openjdk-8-jdk/g' install.sh
          sudo bash ./install.sh
          git clone https://github.com/friendlyarm/repo
          sudo cp repo/repo /usr/bin/
          mkdir -p ./artifact
          sudo swapoff -a

      - name: Download FriendlyWrt source
        run: |
          mkdir project
          cd project
          repo init --depth=1 -u https://github.com/friendlyarm/friendlywrt_manifests -b master-v23.05 \
            -m rk3399.xml --repo-url=https://github.com/friendlyarm/repo --no-clone-bundle
          repo sync -c friendlywrt --no-clone-bundle
          repo sync -c configs --no-clone-bundle
          repo sync -c device/common --no-clone-bundle
          repo sync -c device/friendlyelec --no-clone-bundle
          repo sync -c scripts --no-clone-bundle
          repo sync -c scripts/sd-fuse --no-clone-bundle
          repo sync -c toolchain --no-clone-bundle

      - name: Only keep SSR Plus+ feeds
        run: |
          cd project/friendlywrt
          # 追加自定义 SSR Plus+ feeds
          echo "src-git custom https://github.com/your-repo/ssr-plus-package.git" >> feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig

      - name: Compile FriendlyWrt
        run: |
          cd project/friendlywrt
          [ "${{ matrix.SET }}" == "docker" ] && SUFFIX="-docker"
          make -j$(nproc) || make -j1 V=s

      - name: Create rootfs package
        run: |
          cd project/friendlywrt
          [ "${{ matrix.SET }}" == "docker" ] && SUFFIX="-docker"
          rootfs_filename="rootfs-friendlywrt-23.05${SUFFIX}.tgz"
          tar czf ../../artifact/${rootfs_filename} *
          echo "rootfs_filename=${rootfs_filename}" >> $GITHUB_ENV

      - name: Upload rootfs package
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./artifact/${{ env.rootfs_filename }}
          asset_name: ${{ env.rootfs_filename }}
          tag: ${{ needs.prepare_release.outputs.release_tag }}
          overwrite: true
