name: Build NanoPi M4 FriendlyWrt with SSR Plus+ (Docker/Non-Docker)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 0'  # 每周日 UTC 3:00

jobs:
  build_rootfs_ssr:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        SET: [docker, non-docker]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install -y git wget build-essential libncurses5-dev zlib1g-dev gcc g++ unzip python3

    - name: Download FriendlyWrt rootfs
      run: |
        mkdir -p project
        cd project
        wget -q https://github.com/friendlyarm/friendlywrt/releases/download/v24.10/rootfs-friendlywrt-24.10.tgz
        tar -xzf rootfs-friendlywrt-24.10.tgz -C friendlywrt

    - name: Add SSR Plus+ feed
      run: |
        cd project/friendlywrt
        mkdir -p package/custom
        echo "src-git custom https://github.com/ophub/luci-app-ssr-plus.git" > feeds.conf.custom
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Prepare config
      run: |
        cd project/friendlywrt
        [ "${{ matrix.SET }}" == "docker" ] && SUFFIX="-docker" || SUFFIX=""
        DIRNAME=friendlywrt24${SUFFIX}
        CONFIG=rockchip${SUFFIX}
        cat > .current_config.mk <<EOL
. device/friendlyelec/rk3399/base.mk
TARGET_IMAGE_DIRNAME=${DIRNAME}
TARGET_FRIENDLYWRT_CONFIG=${CONFIG}
EOL
        make defconfig

    - name: Compile
      run: |
        cd project/friendlywrt
        make -j$(nproc) V=s || make -j1 V=s

    - name: Build SD image
      run: |
        cd project/friendlywrt
        if [ -f scripts/make_sdcard.sh ]; then
          ./scripts/make_sdcard.sh
          mv out/*.img ../
        else
          echo "请手动烧录 rootfs 到 SD 卡"
        fi

    - name: Create GitHub release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "FriendlyWrt-SSRPlus-$(date +%Y-%m-%d)"
        draft: false
        prerelease: false

    - name: Upload SD image to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: project/*.img
        asset_name: "NanoPiM4-FriendlyWrt-SSRPlus-${{ matrix.SET }}.img"
        tag: ${{ steps.create_release.outputs.tag_name }}
        overwrite: true
