name: Build FriendlyWrt for NanoPi M4

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        SET: [docker, non-docker]

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Init build env
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget build-essential python3 unzip rsync
          git clone https://github.com/friendlyarm/repo
          sudo cp repo/repo /usr/bin/
          mkdir -p artifact

      - name: Download source (rk3399, v24.10)
        run: |
          mkdir project && cd project
          repo init --depth=1 -u https://github.com/friendlyarm/friendlywrt_manifests -b master-v24.10 \
                   -m rk3399.xml --repo-url=https://github.com/friendlyarm/repo --no-clone-bundle
          repo sync -c friendlywrt --no-clone-bundle
          repo sync -c kernel --no-clone-bundle
          repo sync -c u-boot --no-clone-bundle
          repo sync -c rkbin --no-clone-bundle
          repo sync -c configs --no-clone-bundle
          repo sync -c device/common --no-clone-bundle
          repo sync -c device/friendlyelec --no-clone-bundle
          repo sync -c scripts --no-clone-bundle
          repo sync -c scripts/sd-fuse --no-clone-bundle
          repo sync -c toolchain --no-clone-bundle

      - name: Add SSR Plus+
        run: |
          cd project/friendlywrt
          echo 'src-git helloworld https://github.com/fw876/helloworld' >> feeds.conf.default
          ./scripts/feeds update helloworld
          ./scripts/feeds install luci-app-ssr-plus
          echo "CONFIG_PACKAGE_luci-app-ssr-plus=y" >> .config
          make defconfig

      - name: Build rootfs
        run: |
          cd project/friendlywrt
          make download -j$(nproc)
          make -j$(nproc) || make -j1 V=s

      - name: Build image
        run: |
          cd project
          [ "${{ matrix.SET }}" = "docker" ] && SUFFIX="-docker" || SUFFIX=""
          FILENAME=NanoPi-M4-FriendlyWrt-24.10${SUFFIX}.img
          echo "TARGET_IMAGE_DIRNAME=friendlywrt24${SUFFIX}" > .current_config.mk
          echo "TARGET_FRIENDLYWRT_CONFIG=rockchip${SUFFIX}" >> .current_config.mk
          echo "TARGET_SD_RAW_FILENAME=$FILENAME" >> .current_config.mk
          ./build.sh sd-img
          mv out/$FILENAME ../artifact/
          cd ../artifact
          gzip -9 $FILENAME

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: NanoPi-M4-images
          path: artifact/*.img.gz
