name: Build FriendlyWrt NanoPi M4 (Docker)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Build Docker image for FriendlyWrt
      run: |
        docker build -t friendlywrt-builder -f Dockerfile .

    - name: Create artifact directory
      run: mkdir -p artifact

    - name: Compile FriendlyWrt inside Docker
      run: |
        docker run --rm -it \
          -v ${{ github.workspace }}/friendlywrt:/work/friendlywrt \
          -v ${{ github.workspace }}/artifact:/work/artifact \
          friendlywrt-builder \
          bash -c "
            export PATH=/work/friendlywrt/staging_dir/host/bin:\$PATH
            echo '编译 host 工具链'
            make tools/compile -j$(nproc)
            echo '增量编译 target + 插件'
            NPROC=\$(nproc)
            if [ \$NPROC -gt 4 ]; then JOBS=4; else JOBS=\$NPROC; fi
            make -j\$JOBS V=sc
            echo '打包 SD 镜像'
            FILENAME=NanoPi-M4-FriendlyWrt-24.10.img
            mv bin/targets/rockchip/armv8/\$FILENAME /work/artifact/ || true
            cd /work/artifact && gzip -9 \$FILENAME || true
          "

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: NanoPi-M4-images
        path: artifact/*.img.gz
