name: Build FriendlyWrt for NanoPi M4

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential flex bison gawk gcc-multilib g++-multilib \
            gettext libncurses5-dev libssl-dev python3-distutils \
            rsync unzip file wget git

      - name: Clone FriendlyWrt
        run: |
          git clone https://github.com/friendlyarm/friendlywrt.git friendlywrt
          cd friendlywrt
          ls -l

      - name: Build NanoPi M4 Image
        run: |
          cd friendlywrt
          make distclean
          ./build.sh nanopi_m4.mk

          # 添加 SSR Plus + Passwall + Docker
          cat >> .config <<EOF
          CONFIG_PACKAGE_luci-app-ssr-plus=y
          CONFIG_PACKAGE_luci-app-passwall=y
          CONFIG_PACKAGE_luci-compat=y
          CONFIG_PACKAGE_luci-lib-ipkg=y
          CONFIG_PACKAGE_ipset=y
          CONFIG_PACKAGE_ip-full=y

          # Docker 支持
          CONFIG_PACKAGE_docker=y
          CONFIG_PACKAGE_dockerd=y
          CONFIG_PACKAGE_luci-app-dockerman=y
          CONFIG_PACKAGE_luci-lib-docker=y
          EOF

          make defconfig
          make -j$(nproc)

      - name: Upload SD Image
        uses: actions/upload-artifact@v4
        with:
          name: NanoPi-M4-FriendlyWrt
          path: |
            friendlywrt/out/*.img*
            friendlywrt/bin/targets/**/*.img*
