Run docker run --rm -it \
  docker run --rm -it \
    -v /home/runner/work/Actions-FriendlyWrt/Actions-FriendlyWrt/friendlywrt:/work/friendlywrt \
    -v /home/runner/work/Actions-FriendlyWrt/Actions-FriendlyWrt/artifact:/work/artifact \
    friendlywrt-builder \
    bash -c "
      export PATH=/work/friendlywrt/staging_dir/host/bin:\$PATH
      echo '编译 host 工具链'
      make tools/compile -j$(nproc)
      echo '增量编译 target + 插件'
      NPROC=\$(nproc)
      if [ \$NPROC -gt 4 ]; then JOBS=4; else JOBS=\$NPROC; fi
      make -j\$JOBS V=sc
      echo '打包 SD 镜像'
      FILENAME=NanoPi-M4-FriendlyWrt-24.10.img
      mv bin/targets/rockchip/armv8/\$FILENAME /work/artifact/ || true
      cd /work/artifact && gzip -9 \$FILENAME || true
    "
  shell: /usr/bin/bash -e {0}
the input device is not a TTY
Error: Process completed with exit code 1.
