name: Build FriendlyWrt for NanoPi M4

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Actions-FriendlyWrt repo
        uses: actions/checkout@v3

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
            git build-essential subversion libncurses5-dev zlib1g-dev \
            gawk gcc-multilib flex gettext wget unzip python3 python3-distutils ccache \
            ca-certificates
          # 设置线程数
          echo "export MAKEFLAGS=-j4" >> $GITHUB_ENV

      - name: Clone FriendlyWrt source
        run: |
          rm -rf friendlywrt
          git clone --depth 1 https://github.com/friendlyarm/friendlywrt.git

      - name: Compile FriendlyWrt
        run: |
          cd friendlywrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

          # 自动修改 .config，启用 NanoPi M4 + SSR Plus + Passwall
          cp defconfig .config
          sed -i 's/# CONFIG_PACKAGE_luci-app-ssr-plus is not set/CONFIG_PACKAGE_luci-app-ssr-plus=y/' .config
          sed -i 's/# CONFIG_PACKAGE_luci-app-passwall is not set/CONFIG_PACKAGE_luci-app-passwall=y/' .config

          make defconfig
          make

          mkdir -p ../artifact
          cp bin/targets/sunxi/rockchip/*.img.gz ../artifact/

      - name: Upload SD card image artifact
        uses: actions/upload-artifact@v3
        with:
          name: friendlywrt-nanopi-m4
          path: artifact/*.img.gz
