name: Build FriendlyWrt SD Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget build-essential python3 unzip rsync ccache \
            parted dosfstools e2fsprogs fdisk kmod

      - name: Clone FriendlyWrt
        run: |
          git clone --depth=1 https://github.com/friendlyarm/friendlywrt project/friendlywrt

      - name: Prepare config
        run: |
          cd project/friendlywrt
          cp configs/config_nanopi_m4_defconfig .config
          # 强制启用 SD 镜像选项
          echo "CONFIG_TARGET_IMAGES=y" >> .config
          echo "CONFIG_TARGET_IMAGE_SD=y" >> .config
          make defconfig

      - name: Build
        run: |
          cd project/friendlywrt
          make -j$(nproc) || make -j1 V=s

      - name: Find SD Image
        run: |
          cd project/friendlywrt
          IMG_PATH=$(find bin/targets/rockchip/ -type f -name "*-sdcard.img" | head -n1 || true)
          if [ -z "$IMG_PATH" ]; then
            echo "❌ No SD image found!"
            ls -R bin/targets || true
            exit 1
          fi
          echo "IMG_PATH=$IMG_PATH" >> $GITHUB_ENV

      - name: Upload SD Image
        uses: actions/upload-artifact@v4
        with:
          name: FriendlyWrt-SDImage
          path: ${{ env.IMG_PATH }}
